version: '3.9'

volumes:
  mongo_db:
    external: true
  chroma_db:
    external: true

networks:
  threads:
    external: true

services:
  mongodb:
    hostname: '${MONGO_DB_HOST}'
    image: mongo:5.0
    ports:
      - '${MONGO_DB_EXPOSED_PORT}:${MONGO_DB_PORT}'
    volumes:
      - 'mongo_db:/data/db'
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=anish
    networks:
      threads:
        aliases:
          - ${MONGO_DB_HOST}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      threads:
        aliases:
          - rabbitmq

  chromadb:
    image: chromadb/chroma:0.5.3
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma_db:/chroma/chroma
    networks:
      threads:
        aliases:
          - chromadb